### ISSUE TITLE
[IDEA] fine grid diagram in stats population

### ISSUE THREAD

**Issue by sl5net** [LangLangBart/boonGUI#123]
sometimes i look the replays, and sometimes i try to find  out what the time for 100pop is.
that's not so easy with the grid we have.

maybe a example Screenshots here. i don't know. for example green? that's maybe 100 in 10min or so.
![image](https://user-images.githubusercontent.com/5634759/160669465-0ec8bd90-3b14-41a2-88e7-044bf71a7d12.png)

**Comment by LangLangBart** [comment]
This issue was document by @Imarok in Ticket: [#5088 - Advanced chart/graph features](https://trac.wildfiregames.com/ticket/5088) (21/Mar/18) he recommends to use a `crosshair`.
<img src="https://user-images.githubusercontent.com/92653266/160672014-6183ae43-bff7-4c6c-84c5-6dccb0b3cf3a.png" width="800">

Later it was brought to the attention of @toonijn (Toon Baeyens) when working on a feature for displaying `idle Time` #21

On the 23/Aug/21 he wrote:

> 13:58 < toonijn> For some exponential curves (like trade income or resource count) this would also make them more readable
> 14:00 < Langbart> Yes, Imarok made a ticket with improvements. Another suggestions would be a crosshair, see #5088. You can add your suggestion to the ticket if you like.
> 14:01 < toonijn> Maybe, when I find the time I will take a shot at something like that

I'll leave this ticket open for now and remove the label `Nice-to-have`, but I won't work on it. The bot will close it after a month of inactivity.

**Comment by sl5net** [comment]
i looked into the source. was not easy as i thought first to use a source like this https://canvasjs.com/javascript-charts/chart-cursor-crosshair/ . looks much different to me.
