### ISSUE TITLE
[IDEA] show real rating as tooltip

### ISSUE THREAD

**Issue by sl5net** [LangLangBart/boonGUI#137]
to discuss. as observer i interested to see real rating of a player.

should we use real rating in replays? for observer?

you now all how to modify this rating label text. funny think and i love it. 

maybe show real rating as tooltip?

![image](https://user-images.githubusercontent.com/5634759/166097323-640c3f49-925f-4fdd-bfe2-97cee6930db6.png)

**Comment by LangLangBart** [comment]
Currently, the rating comes from the `commands.txt` file, one could request information about the user from the lobby server see image below for such functions.
* [gui.d.ts](https://github.com/nanihadesuka/autociv/blob/master/gui/gui.d.ts#L678)
<img src="https://user-images.githubusercontent.com/92653266/166106354-8ff68802-b309-45b0-a04d-5b63fbdf7797.jpg" width="600">

If you retrieve the data and compare it with the rating from the `commands.txt`, the rating may be different because the player`s score has gone up/down.

The only way would be to always retrieve the data from the server and use it to display the correct rating, you would never see an incorrect score that was changed by a mod. The problem with this is the number of calls to the server, because every time you watch a replay, a request will be made to the server.

`elexis` made some comments about such function calls and stressed that one should be thinking of the additional traffic this will cause. See link below.
* [D4262](https://code.wildfiregames.com/D4262#181756)

This is the reason I don't want to touch it and will close the issue.
