### ISSUE TITLE
[Feature]: Hero of Persons should listed

### ISSUE THREAD

**Issue by sl5net** [LangLangBart/boonGUI#201]
### Before submitting your Feature Request

- [X] I have searched the [issue tracker](https://github.com/LangLangBart/boonGUI/issues) for a feature request that matches the one I want to file, without success.

### Problem

Hero of Persons is not listed

in Units Tab

### Feature/ Solution

![Screenshot_20221017_124324](https://user-images.githubusercontent.com/5634759/196157969-d2a92b3c-a3e8-4da1-8a3c-0d3a2bee9ffd.png)

**Comment by LangLangBart** [comment]
Hey, the hero might have been excluded by Islan, because he has a portrait in the upper left corner of the screen.


The wish that it should also shows up in the `Units` tab makes sense.
Will make a commit.

<img src="https://raw.githubusercontent.com/LangLangbart/ImagePool/630235465ac679c01fccca315558c4b4b6951308/storage/17_Oct_22_at_15_22_41_SCR-20221017-la1-2.png" width="600">
